spring.application.name=planeacion.backend

spring.datasource.url=jdbc:sqlserver://10.1.30.20:1433;TrustServerCertificate=True
spring.datasource.username=April
spring.datasource.password=Apr1l2023

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


jwt.secret=ClaveSuperSecretaDeMasDe32CaracteresParaJWT_2025_08
jwt.ttlSeconds=3600
